### ISSUE TITLE
Error Loading Application

### ISSUE THREAD

**Issue by deephouseislife** [epinter/tqrespec#17]
java.lang.NullPointerException
	at br.com.pinter.tqdatabase/br.com.pinter.tqdatabase.SkillDAO.lambda$getSkillList$1(Unknown Source)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at br.com.pinter.tqdatabase/br.com.pinter.tqdatabase.SkillDAO.getSkillList(Unknown Source)
	at br.com.pinter.tqdatabase/br.com.pinter.tqdatabase.SkillDAO.preload(Unknown Source)
	at br.com.pinter.tqdatabase/br.com.pinter.tqdatabase.Skills.preload(Unknown Source)
	at br.com.pinter.tqrespec/br.com.pinter.tqrespec.Main$2.call(Unknown Source)
	at br.com.pinter.tqrespec/br.com.pinter.tqrespec.Main$2.call(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

OS Windows 10 v1903 and playing the game on Steam.

**Comment by epinter** [comment]
Sorry the delay ... The game database is modded ?
Can you get the tqrespec.log (in %TEMP% directory) ?

**Comment by deephouseislife** [comment]
I downloded mods from steam workshop, such as xmax,lootplus and stuff. I didnt changed/edited anything from the game folder.
also there is tqrespec.log but it is empty. zero bytes.

**Comment by epinter** [comment]
The application is crashing after reading the database and during skills data preload, it's weird. I didn't manage to reproduce this bug yet. Need to work on it.

**Comment by epinter** [comment]
When you have some time, run this build... There are only few code changes (nothing that solves this bug), but should show the line numbers so I can know exactly where is crashing.

https://www119.zippyshare.com/v/sokzwJxE/file.html

**Comment by deephouseislife** [comment]
![Adsız](https://user-images.githubusercontent.com/54971659/67152984-0adc7580-f2ea-11e9-859f-e94a9e91d3ca.jpg)

**Comment by epinter** [comment]
This issue is open for a long time, but maybe you are interest to try this build:

https://mega.nz/#!5NlVzQAY!-VzPs_VLu_rgUG6RHfcroZZ805xA2go49lNSf0cY7Dg

This build is from a dev branch, so it's not completely tested yet. Contains a possible fix for your problem.

If the problem persistd and you have some time, generate a debug log with the following command.

First, open CMD or Powershell, and go to the directory when TQRespec,exe is. Then run the command

`.\TQRespec.exe --debug=5`

The log should be in "%TEMP%\tqrespec.log", its size is around 130KB.

Thanks you.

**Comment by epinter** [comment]
This build fixes the problem:
https://1drv.ms/u/s!Al6bs7S_f0Jth3ChUopswipEN--K?e=ndqHQh
