### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by gabewindy** [epinter/tqrespec#18]
Hi when I run the version 0.7.2 I kept running into the following error:

java.lang.ArrayIndexOutOfBoundsException: Index 30501388 out of bounds for length 76498
	at br.com.pinter.tqdatabase/br.com.pinter.tqdatabase.ArzFile.recordMetadataGet(Unknown Source)
	at br.com.pinter.tqdatabase/br.com.pinter.tqdatabase.ArzFile.readRecordsTable(Unknown Source)
	at br.com.pinter.tqdatabase/br.com.pinter.tqdatabase.ArzFile.<init>(Unknown Source)
	at br.com.pinter.tqdatabase/br.com.pinter.tqdatabase.ArzFile.<init>(Unknown Source)
	at br.com.pinter.tqdatabase/br.com.pinter.tqdatabase.Database.<init>(Unknown Source)
	at br.com.pinter.tqdatabase/br.com.pinter.tqdatabase.Database.<init>(Unknown Source)
	at br.com.pinter.tqrespec/br.com.pinter.tqrespec.tqdata.Db.initialize(Unknown Source)
	at br.com.pinter.tqrespec/br.com.pinter.tqrespec.Main$2.call(Unknown Source)
	at br.com.pinter.tqrespec/br.com.pinter.tqrespec.Main$2.call(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

I've followed the instruction here https://github.com/epinter/tqrespec#running-without-the-game-installed and placed the "Database" and "Text" folders under a folder "gamedata". What could be the problem?

Thanks in advance :)

**Comment by epinter** [comment]
You have done everything correctly. Some protections are missing in the code. Other user experienced another problem related to database/resources loading. You can try the file I posted in the issue https://github.com/epinter/tqrespec/issues/17.

https://www119.zippyshare.com/v/sokzwJxE/file.html

Unfortunately, I didnt have time to fix these bugs, because I started a lot of rework in the code and didn't finish. I will resume all the work in a few days. The link above contains new code, maybe fixes something for you. Your database and text files would help a lot for me, so I can compare and determine what is different (game files or environment).

Thanks for your time reporting this problem.

**Comment by epinter** [comment]
Please, use this build to generate a debug log, running it with:

`.\TQRespec.exe --debug=5`

https://mega.nz/#!5NlVzQAY!-VzPs_VLu_rgUG6RHfcroZZ805xA2go49lNSf0cY7Dg
