### ISSUE TITLE
Rename Error

### ISSUE THREAD

**Issue by toletroi** [epinter/tqrespec#21]
Everything else work fine except the rename option.After I save it to new save,can't find it in character selection menu.Open that new save in TQ respec popup 2 error message.

first message:
br.com.pinter.tqrespec.core.UnhandledRuntimeException: Error loading character
	at br.com.pinter.tqrespec/br.com.pinter.tqrespec.save.player.Player.loadPlayer(Player.java:68)
	at br.com.pinter.tqrespec/br.com.pinter.tqrespec.gui.MainController$10.call(MainController.java:430)
	at br.com.pinter.tqrespec/br.com.pinter.tqrespec.gui.MainController$10.call(MainController.java:427)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: br.com.pinter.tqrespec.core.UnhandledRuntimeException: java.lang.NullPointerException
	at br.com.pinter.tqrespec/br.com.pinter.tqrespec.save.FileParser.parse(FileParser.java:99)
	at br.com.pinter.tqrespec/br.com.pinter.tqrespec.save.player.PlayerParser.loadPlayer(PlayerParser.java:167)
	at br.com.pinter.tqrespec/br.com.pinter.tqrespec.save.player.Player.loadPlayer(Player.java:61)
	... 5 more
Caused by: java.lang.NullPointerException
	at br.com.pinter.tqrespec/br.com.pinter.tqrespec.save.FileParser.prepareBufferForRead(FileParser.java:84)
	at br.com.pinter.tqrespec/br.com.pinter.tqrespec.save.player.PlayerParser.fillBuffer(PlayerParser.java:141)
	at br.com.pinter.tqrespec/br.com.pinter.tqrespec.save.FileParser.parse(FileParser.java:94)
	... 7 more

second message:

java.lang.IllegalArgumentException: Invalid data "myPlayerName"
	at br.com.pinter.tqrespec/br.com.pinter.tqrespec.save.ChangesTable.setString(ChangesTable.java:129)
	at br.com.pinter.tqrespec/br.com.pinter.tqrespec.save.player.PlayerWriter.copyCurrentSave(PlayerWriter.java:194)
	at br.com.pinter.tqrespec/br.com.pinter.tqrespec.gui.MainController$4.call(MainController.java:287)
	at br.com.pinter.tqrespec/br.com.pinter.tqrespec.gui.MainController$4.call(MainController.java:283)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:832)

TQRespec version 
-0.8.0

Operating System
- Windows 10

Game version (please complete the following information):***
- Titan Quest AE v2.9

DLCs installed (please complete the following information):
-Ragnarok
-Atlantis

**Comment by epinter** [comment]
This problem is not happening with my characters. Can you send me your player.chr so I can reproduce ?

**Comment by epinter** [comment]
This error indicates the software was unable to access the savegame. Please check your antivirus, windows controlled file access feature, or any other security software that can block access to the save game. If the problem persists, please send me more information, like the savegame (player.chr).
