### ISSUE TITLE
add support for gog version

### ISSUE THREAD

**Issue by 648643579** [epinter/tqrespec#3]
Hi, can you add support for the gog version?
"C:\GOG Games\Titan Quest - Anniversary Edition"
[save_paths.zip](https://github.com/epinter/tqrespec/files/3364536/save_paths.zip)

ERROR:
```
java.lang.RuntimeException: Error loading database.
	at br.com.pinter.tqrespec/br.com.pinter.tqrespec.tqdata.Db.initialize(Unknown Source)
	at br.com.pinter.tqrespec/br.com.pinter.tqrespec.Main$1.call(Unknown Source)
	at br.com.pinter.tqrespec/br.com.pinter.tqrespec.Main$1.call(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.FileNotFoundException: Game path not detected
	at br.com.pinter.tqrespec/br.com.pinter.tqrespec.tqdata.GameInfo.getGamePath(Unknown Source)
	... 6 more
```

**Comment by epinter** [comment]
Thank you. Actually GOG is supported but it's not working.

**Comment by epinter** [comment]
Can you try this build ?

https://drive.google.com/file/d/1xYvmbOi9JbXhq7HxXWIOMFA_b5naKsoF/view?usp=sharing

**Comment by 648643579** [comment]
yes, work!

**Comment by epinter** [comment]
Thank you for the help!

**Comment by epinter** [comment]
Fixed by https://github.com/epinter/tqrespec/commit/925579b73a8515ca4aff470dac3136e30b07ad9a
