### ISSUE TITLE
Unhandled exception occurred

### ISSUE THREAD

**Issue by Levine83** [epinter/tqrespec#41]
Hey, I get an error when I try to load my character into the app.
It states " save.InvalidVariableException: variable 'altMoney' not found for platform 'WINDOWS'

Details:
br.com.pinter.tqrespec.core.UnhandledRuntimeException: Error loading character
	at br.com.pinter.tqrespec/br.com.pinter.tqrespec.save.player.Player.loadPlayer(Player.java:105)
	at br.com.pinter.tqrespec/br.com.pinter.tqrespec.gui.MainController$6.call(MainController.java:372)
	at br.com.pinter.tqrespec/br.com.pinter.tqrespec.gui.MainController$6.call(MainController.java:369)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Task.java:1426)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: br.com.pinter.tqrespec.save.InvalidVariableException: variable 'altMoney' not found for platform 'WINDOWS'
	at br.com.pinter.tqrespec/br.com.pinter.tqrespec.save.player.PlayerFileVariable.valueOf(PlayerFileVariable.java:180)
	at br.com.pinter.tqrespec/br.com.pinter.tqrespec.save.player.PlayerParser.getFileVariable(PlayerParser.java:270)
	at br.com.pinter.tqrespec/br.com.pinter.tqrespec.save.FileParser.validateBlockType(FileParser.java:241)
	at br.com.pinter.tqrespec/br.com.pinter.tqrespec.save.FileParser.parseBlock(FileParser.java:181)
	at br.com.pinter.tqrespec/br.com.pinter.tqrespec.save.FileParser.parseAllBlocks(FileParser.java:303)
	at br.com.pinter.tqrespec/br.com.pinter.tqrespec.save.FileParser.parse(FileParser.java:111)
	at br.com.pinter.tqrespec/br.com.pinter.tqrespec.save.FileParser.load(FileParser.java:144)
	at br.com.pinter.tqrespec/br.com.pinter.tqrespec.save.player.Player.loadPlayer(Player.java:96)

Can't be sure if I'm going something wrong as I've never used this before.
Thank ya.

**Comment by Gethsemane2** [comment]
I get this error as well. It coincided with the latest update which included a new currency, Electrum.

**Comment by epinter** [comment]
An update is needed to support the new save game format, please see this issue: https://github.com/epinter/tqrespec/issues/40
