### ISSUE TITLE
Error loading character

### ISSUE THREAD

**Issue by QStormDS** [epinter/tqrespec#42]
**Describe the bug**
After selecting my char the following error occurs.

***To Reproduce***
1. Start TQ Respec
2. Click on the Character combobox
3. Select the Character

***Expected behavior***
The character should be loaded

***Error message (detail)***
br.com.pinter.tqrespec.core.UnhandledRuntimeException: Error loading character
	at br.com.pinter.tqrespec/br.com.pinter.tqrespec.save.player.Player.loadPlayer(Player.java:106)
	at br.com.pinter.tqrespec/br.com.pinter.tqrespec.gui.MainController$6.call(MainController.java:374)
	at br.com.pinter.tqrespec/br.com.pinter.tqrespec.gui.MainController$6.call(MainController.java:371)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Task.java:1426)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: br.com.pinter.tqrespec.save.InvalidVariableException: variable 'buffSkillName' not found for platform 'WINDOWS'
	at br.com.pinter.tqrespec/br.com.pinter.tqrespec.save.player.PlayerFileVariable.valueOf(PlayerFileVariable.java:195)
	at br.com.pinter.tqrespec/br.com.pinter.tqrespec.save.player.PlayerParser.getFileVariable(PlayerParser.java:275)
	at br.com.pinter.tqrespec/br.com.pinter.tqrespec.save.FileParser.validateBlockType(FileParser.java:246)
	at br.com.pinter.tqrespec/br.com.pinter.tqrespec.save.FileParser.parseBlock(FileParser.java:182)
	at br.com.pinter.tqrespec/br.com.pinter.tqrespec.save.FileParser.parseAllBlocks(FileParser.java:324)
	at br.com.pinter.tqrespec/br.com.pinter.tqrespec.save.FileParser.parse(FileParser.java:112)
	at br.com.pinter.tqrespec/br.com.pinter.tqrespec.save.FileParser.load(FileParser.java:145)
	at br.com.pinter.tqrespec/br.com.pinter.tqrespec.save.player.Player.loadPlayer(Player.java:96)
	... 5 more

***TQRespec version (please complete the following information):***
- 0.11.1

***Operating System (please complete the following information):***
- Windows 10 64 bit

***Game version (please complete the following information):***
- Titan Quest Anniversary Edition 2.10.20820 (Steam)

***DLCs installed (please complete the following information):***
-Ragnarok?
-Atlantis?

***Additional context***
[Player.zip](https://github.com/epinter/tqrespec/files/8860103/Player.zip)

**Comment by epinter** [comment]
More changes from new version... I will work on it today I try to post here a test build soon... Thanks!

**Comment by epinter** [comment]
Can you test ? Just to be sure...

Download link:
https://1drv.ms/u/s!AqbcmbBetf3hgQpgdtcDOXs0rYKj?e=L8WLUd

**Comment by QStormDS** [comment]
Tested it. This version is working. Didn't get the error. As far as I can see the properties and values looks good. I did changes and saved it... The changes are visible in the game.

**Comment by epinter** [comment]
> Tested it. This version is working. Didn't get the error. As far as I can see the properties and values looks good. I did changes and saved it... The changes are visible in the game.

Great, so  I will prepare a release. Thank you for the help.
