### ISSUE TITLE
Change Masteries?

### ISSUE THREAD

**Issue by Jayshua83** [epinter/tqrespec#5]
Will you be able to make it so we can reset out masteries back to 0 or none? I would really like to be able to change my mastery choices / change class!

Thanks!

**Comment by epinter** [comment]
I didn't implement it yet. But I plan to add the feature to remove the mastery.

**Comment by epinter** [comment]
Do you want to test a version with mastery removal feature ? I think I would not take too long to implement this as a test...

**Comment by Jayshua83** [comment]
Sure. I can do that!

Very easy with your mod since I can create copies of my toon anytime! lol :)

**Comment by epinter** [comment]
I still need to decide the UI and how the feature will be available, because I don't want 'cheats' in the application. I'm not so sure if remove mastery is a cheat, initially I don't think it is but need to think about it anyway.

Be careful, I didn't test yet... 

https://drive.google.com/file/d/1YnVM0uzgol-cL4WO2b-P4DSCiKW7yVf5/view?usp=sharing

**Comment by Jayshua83** [comment]
> I still need to decide the UI and how the feature will be available, because I don't want 'cheats' in the application. I'm not so sure if remove mastery is a cheat, initially I don't think it is but need to think about it anyway.
> 
> Be careful, I didn't test yet...
> 
> https://drive.google.com/file/d/1YnVM0uzgol-cL4WO2b-P4DSCiKW7yVf5/view?usp=sharing

I have tried downloading this several times and Google Drive just load forever... Very odd.. I use GD all the time with no issues.

**Comment by epinter** [comment]
Another version for you to test:
https://mega.nz/#!dI9kDQRL!nJX9XVMh8HdYdEebngprsOE-IlWc412J8BrsAJd1x0E

**Comment by Jayshua83** [comment]
java.lang.RuntimeException: java.lang.IllegalStateException: An invalid variable (scrollName) was found in block 817597 (PlayerHotSlot), aborting.
	at br.com.pinter.tqrespec/br.com.pinter.tqrespec.save.PlayerData.loadPlayer(Unknown Source)
	at br.com.pinter.tqrespec/br.com.pinter.tqrespec.gui.MainController$10.call(Unknown Source)
	at br.com.pinter.tqrespec/br.com.pinter.tqrespec.gui.MainController$10.call(Unknown Source)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: An invalid variable (scrollName) was found in block 817597 (PlayerHotSlot), aborting.
	at br.com.pinter.tqrespec/br.com.pinter.tqrespec.save.PlayerParser.parseBlock(Unknown Source)
	at br.com.pinter.tqrespec/br.com.pinter.tqrespec.save.FileParser.parseAllBlocks(Unknown Source)
	at br.com.pinter.tqrespec/br.com.pinter.tqrespec.save.FileParser.parse(Unknown Source)
	at br.com.pinter.tqrespec/br.com.pinter.tqrespec.save.PlayerParser.loadPlayer(Unknown Source)
	... 6 more

**Comment by epinter** [comment]
Can you send me your save ?

I hope I fixed the scrollName ...
https://mega.nz/#!oQ1UBSjB!s5Mr8XfGIjIVBh9cJg7QZuzDcqGHC6fqLxrKHmy2Y9w

**Comment by epinter** [comment]
dev0712.2 - with masteries removal, and fixed scrollName problem
https://mega.nz/#!JU9QlSyb!U2wH-pzWFKfowcRmUGUoxAS7SSevJ-3N-FXy4sMQZxU

**Comment by Jayshua83** [comment]
Seems like that worked. It reset just fine.

Not sure what else needs testing...
